from project_euler.decorators import print_run_time


@print_run_time
def distinct_powers_a_b(limit: int) -> int:
    return len({a**b for a in range(2, limit + 1) for b in range(2, limit + 1)})


if __name__ == "__main__":
    print("How many distinct terms are in the sequence generated by a**b for 2<=a<=100 and 2<=b<=100?")
    limit = 100
    print(distinct_powers_a_b(limit))
